"""added document table

Revision ID: f1882bc23a1d
Revises: 88d3012fde89
Create Date: 2025-03-10 23:37:52.752865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel




# revision identifiers, used by Alembic.
revision: str = 'f1882bc23a1d'
down_revision: Union[str, None] = '88d3012fde89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
