services:
  ollama:
    image: ollama/ollama:0.5.11
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh:ro
    networks:
      - smartdoc-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    tty: true
  
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartdoc-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./.envs/.local/.pgadmin
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - smartdoc-net

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
      - "5540:8001"
    volumes:
      - redis_data:/data
    networks:
      - smartdoc-net
  
  flower:
    image: mher/flower
    container_name: flower
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - redis
    volumes:
    - ./entrypoint-flower.sh:/entrypoint-flower.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint-flower.sh"]
    networks:
      - smartdoc-net

networks:
  smartdoc-net:
    driver: bridge

volumes:
  ollama_data:
    driver: local
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  redis_data:
    driver: local
